// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
    // seed: 'tsx prisma/seed.ts',
    // seed: 'tsx prisma/seed-icd10.ts',
    // seed: 'tsx prisma/seed-medication.ts',
    seed: 'tsx prisma/seed-sugerencias.ts',
  },
  datasource: {
    url: process.env['DATABASE_URL'],
  },
});
